# Generated by Django 6.0.3 on 2026-04-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企业/单位名称')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='所在城市')),
                ('description', models.TextField(blank=True, verbose_name='企业简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('age_discrimination', '35 岁以上就业歧视观察榜'), ('gender_discrimination', '性别歧视观察榜'), ('pua_despotism', '职场 PUA 专制观察榜'), ('overwork_exploitation', '职场过劳剥削观察榜')], db_index=True, max_length=50, verbose_name='榜单分类')),
                ('reason', models.TextField(max_length=2000, verbose_name='投票理由/评价')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='是否匿名投票')),
                ('device_fingerprint', models.CharField(help_text='浏览器指纹识别', max_length=256, verbose_name='设备指纹')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.company', verbose_name='目标企业')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='accounts.customuser', verbose_name='投票用户')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'db_table': 'vote',
                'unique_together': {('category', 'company', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档')], max_length=20, verbose_name='文件类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='voting.vote', verbose_name='关联投票')),
            ],
            options={
                'verbose_name': '证据材料',
                'verbose_name_plural': '证据材料',
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='VoteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('total_votes', models.IntegerField(default=0, verbose_name='总票数')),
                ('vote_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='得票率%')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.company')),
            ],
            options={
                'verbose_name': '投票统计',
                'verbose_name_plural': '投票统计',
                'db_table': 'vote_statistics',
                'ordering': ['-vote_rate'],
                'unique_together': {('category', 'company')},
            },
        ),
    ]
